name: Increment Minor Version

on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  contents: write

jobs:
  update-minor-version:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js (for version handling)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Increment minor version
        run: |
          # Extrahiere die aktuelle Versionsnummer aus readme.txt
          version=$(grep -oP '(?<=^Version: )\d+\.\d+\.\d+' readme.txt)
          echo "Current version: $version"

          # Zerlege die Version und erhöhe die Minor-Nummer
          IFS='.' read -r major minor patch <<< "$version"
          minor=$((minor + 1))
          patch=0
          new_version="$major.$minor.$patch"
          echo "New version: $new_version"

          # Aktualisiere die Version in readme.txt
          sed -i "s/^Version: .*/Version: $new_version/" readme.txt
          echo "Updated readme.txt with version: $new_version"

          # Aktualisiere die Version in README.md
          sed -i "s/^Version: .*/Version: $new_version/" README.md
          echo "Updated README.md with version: $new_version"

          # Zeige die aktualisierten Dateien (optional)
          echo "Content of readme.txt:"
          cat readme.txt
          echo "Content of README.md:"
          cat README.md

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add readme.txt README.md
          git commit -m "Increment minor version to $new_version"
          git push origin main
