name: Increment Version

on:
  push:
    branches:
      - dev
      
permissions:
  contents: write
  
jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js (for version handling)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Extract version from package.json
        id: extract_version  # ID für die Referenzierung
        run: |
          # Hol die Versionsnummer aus package.json
          version=$(node -p "require('./package.json').version")
          echo "Current version: $version"

          # Zerlege die Version und erhöhe die Minor-Nummer
          IFS='.' read -r major minor patch <<< "$version"
          patch=$((patch + 1))
          new_version="$major.$minor.$patch"
          echo "New version: $new_version"

          # Aktualisiere die Version in package.json
          node -e "const fs = require('fs'); const version = '$new_version'; const packageJson = require('./package.json'); packageJson.version = version; fs.writeFileSync('./package.json', JSON.stringify(packageJson, null, 2));"
          echo "Updated package.json with version: $new_version"

          # Aktualisiere die Version in README.md
          sed -i "s/Version: .*/Version: $new_version/" README.md
          echo "Updated README.md with version: $new_version"

      - name: Save new version to an environment variable
        env:
          NEW_VERSION: ${{ steps.extract_version.outputs.new_version }}
        run: |
          echo "New version saved: $NEW_VERSION"
        
      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add package.json README.md
          git commit -m "Increment version to $NEW_VERSION"
          git push
